title: BSM
description: Bundled Software Manager

markdown: kramdown

remote_theme: pmarsceill/just-the-docs

search_enabled: true

aux_links:
  'BSM on GitHub':
    - //github.com/bsmsoft/bsm

footer_content: 'Copyright &copy; 2017-2019 BSM Soft. Distributed by the <a href="https://github.com/bsmsoft/bsm/tree/master/LICENSE.txt">MIT license.</a>'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
